[tool.black]
line-length = 140
target-version = ["py38"]

[tool.semantic_release]
version_variables = ["common/constants.py:APP_VERSION"]
commit_author = "vmaas-bot <40663028+vmaas-bot@users.noreply.github.com>"

[tool.isort]
profile = "black"
